# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'm5-learning-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for m5-learning-app
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
end
