# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DB-M1-Firebase-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DB-M1-Firebase-Demo
  pod 'Firebase/Firestore'
end
